image: node:16

stages:
  - test
  - pages

test:
  stage: test
  script:
    - npm install
    - npm run jest
  only:
    - main

pages:
  stage: deploy
  script:
    # - rm -rf public
    # - mkdir public
    # - cp -r ./docs public
    # -------
    - npm install
    - npm run jsdoc
    - rm -rf public
    - cp -r ./docs public

  artifacts:
    paths:
      - public
  only:
    - main
