image: node:16

stages:
  - test
  - pages

test:
  stage: test
  script:
    - npm install
    - npm run jest
    # Check this: https://docs.gitlab.com/ee/user/project/merge_requests/test_coverage_visualization.html
  only:
    - main

pages:
  stage: pages
  script:
    # - rm -rf public
    # - mkdir public
    # - cp -r ./docs public
    # -------
    - npm install
    - npm run jsdoc
    - rm -rf public
    - cp -r ./docs public

  artifacts:
    paths:
      - public
  only:
    - main
