image: node:16

stages:
  - test
  - doc

test:
  stage: test
  script:
    - npm install
    - npm run test
  only:
    - main

doc:
  stage: doc
  script:
    # - rm -rf public
    # - mkdir public
    # - cp -r ./docs public
    # -------
    - npm install
    - npm run jsdoc
    - rm -rf public
    - cp -r ./docs public

  artifacts:
    paths:
      - public
  only:
    - main
